### ISSUE TITLE
The Jekyll binary jekyll is not valid

### ISSUE THREAD

**Issue by nasht00** [Arcath/jekyll-atom#37]
There isn't much information about what should the value be for "Build Command".

When I use the terminal, I type `bundle exec jekyll build` or `bundle exec jekyll serve`  
But entering this line does not help, it still says it's not valid.

**Comment by Arcath** [comment]
Build Command is an array starting with the binary followed by each argument separated by , so in your case `bundle, exec, jekyll, build`.

I have seen issues with nodes child process not picking up on your PATH correctly so you might have to change `bundle` to `/path/to/bundle/binary`

**Comment by rogatty** [comment]
On Windows I had to set it to `C:\Ruby22\bin\jekyll.bat, serve`

**Comment by hufan-Akari** [comment]
I have the same problem.
i run it on OS X 10.11 and leave the default 'Build Command': `jekyll, build`
it's OK when i type the jekyll commands in the terminal.

I installed the jekyll with the command `sudo gem install -n /usr/local/bin jekyll -v 3.1.6` 
Because the  /usr/bin is not writable under rootless mode.
Maybe that's why do I run into the problem ?

**Comment by Arcath** [comment]
Atom doesn't get your full path. if you run `which jekyll` in terminal it will tell you the full path to the jekyll executable.
