### ISSUE TITLE
The Jekyll Binary jekyll is not valid.

### ISSUE THREAD

**Issue by resuly** [Arcath/jekyll-atom#66]
Problem here:
![20170411212500](https://cloud.githubusercontent.com/assets/3870826/24911427/70ceaafc-1efd-11e7-84ef-c306e1f8286d.jpg)

System : Window 10 x64
My setting:
![20170411212514](https://cloud.githubusercontent.com/assets/3870826/24911474/9fedf856-1efd-11e7-9b92-d58a532e293d.jpg)

However, `E:\Ruby23-x64\bin\jekyll.bat build` works in CMD.

What should I do for building correctly? Thank you.

**Comment by Arcath** [comment]
You need a comma between the path to your bat file and the word build. The
setting is actually an array with the binary first and the options after.

On 11 Apr 2017 2:29 p.m., "resuly" <notifications@github.com> wrote:

Problem here:
[image: 20170411212500]
<https://cloud.githubusercontent.com/assets/3870826/24911427/70ceaafc-1efd-11e7-84ef-c306e1f8286d.jpg>

System : Window 10 x64
My setting:
[image: 20170411212514]
<https://cloud.githubusercontent.com/assets/3870826/24911474/9fedf856-1efd-11e7-9b92-d58a532e293d.jpg>

However, E:\Ruby23-x64\bin\jekyll.bat build works in CMD.

What should I do for building correctly? Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Arcath/jekyll-atom/issues/66>, or mute the thread

**Comment by resuly** [comment]
Thank you. It works after I reboot the PC.

**Comment by lief-y** [comment]
Tries all suggestions, still couldn't get it work. Any solution for Windows 7?

I started atom from the terminal, set up the absolute path C:\Ruby25-x64\bin\jekyll.bat, build and check the validity of the path. Still get the message

```
Jekyll Binary Incorrect
The Jekyll Binary jekyll is not valid.
Please go into Settings and change it
```
